weights: ./runs/train/MIAP_person_detection/weights/best.pt
cfg: ./model/yolov7-tiny.yaml
data: ./data/SIGGI_1.yaml
hyp: ./model/yolov7/data/hyp.scratch.tiny.yaml
epochs: 50
batch_size: 32
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: true
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train/SIGGI_target_detection
entity: null
name: SIGGI_1
exist_ok: false
quad: true
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: true
early_stop: false
world_size: 1
global_rank: -1
save_dir: runs/train/SIGGI_target_detection/SIGGI_1
total_batch_size: 32
